[pytest]
# "Опция для автоматического добавления флагов"
addopts = -s -v
python_files = test*.py
python_classes  = Test*
python_functions = test*

markers =
    courses: для тестов, связанных с курсами
    regression: для регрессионных тестов
    authorization: для авторизации
    registration: для регистрации
    dashboard: Маркировка для тестов, связанных с рабочей панелью.
